### ISSUE TITLE
NC is non-free

### ISSUE THREAD

**Issue by TechnologyClassroom** [captainzero93/Protect-Images-from-AI-PixelGuard#1]
Non-commercial (NC) clauses are non-free as they are not free software according to the [FSF](https://www.gnu.org/philosophy/free-sw.html#selling), open source according to the [OSI](https://opensource.org/osd#free-redistribution), or free culture according to [Freedom Defined](https://freedomdefined.org/Definition).  I would recommend using CC-BY-SA-4.0, CC-BY-4.0, or CC-0-1.0 instead which are free culture Creative Commons licenses or one of the GPL licenses.

**Comment by captainzero93** [comment]
Thank you for making me aware, I thought this licence allowed non commercial use with credit

**Comment by TechnologyClassroom** [comment]
It does. This won't be integrated into camera apps or placed in Linux distribution repositories. You might see a handful of patches, but the project won't grow beyond these walls. NC licenses are a dead-end that stops right here unless you change them.

**Comment by captainzero93** [comment]
CC-BY-4.0 is now the licence, hope to see some great improvements soon! Thank you for letting me know
