### ISSUE TITLE
Add image examples in the readme

### ISSUE THREAD

**Issue by dgacias** [captainzero93/Protect-Images-from-AI-PixelGuard#2]
Hey! Just a little suggestion...

Can you add a couple of original images and their tampered versions so we can see if there are any real differences that matter without having to download and prepare the project?

Thanks!

**Comment by captainzero93** [comment]
done, the uploaded protected image is using the lighter preset

**Comment by captainzero93** [comment]
I hope that update has helped, I'll close this Issue for now 
" Please note this is using the "lighter" preset from the GUI, using the sliders all effects can be modified on intensity. (For instance, I understand the QR code might look too obtrusive for some users by defaults) "
